"use client";

import { motion } from "framer-motion";
import { ArrowRight, Bot, Layers3, Network, Plug, Shield, Sparkles, Target } from "lucide-react";
import Reveal from "./Reveal";
import JourneyEngine3D from "./JourneyEngine3D";

const PHASES = [
  ["01", "Choose the move", "Destination, course, university fit and career target become one working context."],
  ["02", "Secure the move", "Applications, funding, visa and deadlines are sequenced around your route."],
  ["03", "Build career capital", "Skills, projects, evidence and network turn study time into career leverage."],
  ["04", "Land the role", "Target roles, employers, applications and interviews connect back to the outcome."],
];
const ECOSYSTEM = [["Discover", "Universities, courses and country intelligence"], ["Prepare", "Email, calendar and document workflows"], ["Move", "Housing, visa and arrival services"], ["Career", "Jobs, networking and employer pathways"]];

export default function HomeShowcase({ onNavigate }: { onNavigate?: (view: string) => void }) {
  return <>
    <section className="relative w-full border-t border-[var(--shield-border)] py-20 sm:py-24">
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <Reveal className="max-w-3xl"><Eyebrow><Layers3 className="h-3.5 w-3.5" />Why this exists</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">The problem is not a lack of information. It is a lack of continuity.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[var(--shield-text-dim)] sm:text-base">Students move between university portals, spreadsheets, consultants, email, visa checklists, job boards and networking tools. Each system sees one slice. AbroadShield is designed around the journey itself.</p></Reveal>
        <Reveal delay={.08} className="mt-10"><div className="grid gap-3 lg:grid-cols-[.72fr_1.28fr]"><div className="rounded-[24px] border border-[var(--shield-border)] bg-[var(--shield-ink-2)] p-5"><div className="text-[9px] font-bold uppercase tracking-[.2em] text-[var(--shield-text-faint)]">The fragmented stack</div><div className="mt-5 space-y-2">{["Study choice", "Applications", "Visa & relocation", "Life during study", "Networking & jobs"].map((item, i) => <motion.div key={item} initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="flex items-center gap-3 rounded-xl border border-[var(--shield-border)] bg-[oklch(0.12_0.016_165)] px-3 py-2.5"><span className="text-[8px] font-bold text-[var(--shield-text-faint)]">0{i + 1}</span><span className="text-[11px] font-medium text-[var(--shield-text-dim)]">{item}</span></motion.div>)}</div></div><div className="relative overflow-hidden rounded-[24px] border border-[oklch(0.74_0.17_162/.22)] bg-[oklch(0.15_0.018_165)] p-6 sm:p-7"><div className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-[oklch(0.74_0.17_162/.09)] blur-3xl"/><div className="relative"><div className="text-[9px] font-bold uppercase tracking-[.2em] text-[oklch(0.85_0.19_158)]">The AbroadShield thesis</div><h3 className="mt-3 max-w-xl text-2xl font-semibold sm:text-3xl">One context layer that carries the student from decision to career.</h3><p className="mt-4 max-w-xl text-sm leading-6 text-[var(--shield-text-dim)]">The product does not replace every service. It gives the student one strategic layer that understands what happened, what matters next and where an agent can safely help.</p><div className="mt-6 flex flex-wrap gap-2">{["Profile", "Journey", "Agent", "Evidence", "Career"].map((item) => <span key={item} className="rounded-full border border-[var(--shield-border)] bg-[oklch(0.1_0.013_165)] px-3 py-1.5 text-[9px] text-[var(--shield-text-dim)]">{item}</span>)}</div></div></div></div></Reveal>
      </div>
    </section>

    <section className="relative w-full py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="mb-7 max-w-2xl"><Eyebrow><Bot className="h-3.5 w-3.5" />See the product idea</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your AI should understand the route.</h2><p className="mt-3 text-sm leading-6 text-[var(--shield-text-dim)]">Context enters the engine. The journey sets priority. Evidence informs the next move. You stay in control.</p></div><JourneyEngine3D /></Reveal></div></section>

    <section id="journey" className="relative w-full border-t border-[var(--shield-border)] py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal className="max-w-3xl"><Eyebrow><Target className="h-3.5 w-3.5"/>The full journey</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Four phases. One evolving strategy.</h2><p className="mt-3 text-sm leading-6 text-[var(--shield-text-dim)]">The route stays visible while the current mission changes.</p></Reveal><Reveal delay={.08} className="mt-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{PHASES.map(([n, title, detail], i) => <motion.button key={n} type="button" onClick={() => onNavigate?.("journey")} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ delay: i * .06 }} whileHover={{ y: -4 }} className="group rounded-[20px] border border-[var(--shield-border)] bg-[oklch(0.15_0.02_165/.42)] p-5 text-left transition hover:border-[oklch(0.74_0.17_162/.36)] hover:bg-[oklch(0.18_0.022_165/.68)]"><div className="text-[9px] font-semibold tracking-[.18em] text-[var(--shield-text-faint)]">{n}</div><h3 className="mt-7 text-base font-semibold">{title}</h3><p className="mt-2 text-[11px] leading-5 text-[var(--shield-text-dim)]">{detail}</p><span className="mt-4 inline-flex items-center gap-1 text-[9px] font-semibold uppercase tracking-[.13em] text-[oklch(0.78_0.08_165)]">Open cockpit <ArrowRight className="h-3 w-3"/></span></motion.button>)}</div></Reveal></div></section>

    <section className="relative w-full py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="grid gap-6 lg:grid-cols-[1fr_1fr] lg:items-center"><div className="relative overflow-hidden rounded-[24px] border border-[var(--shield-border)] bg-[radial-gradient(circle_at_50%_40%,oklch(0.28_0.04_165/.45),oklch(0.1_0.013_165)_68%)] p-6"><div className="absolute inset-0 as-bg-grid opacity-50"/><div className="relative grid grid-cols-2 gap-2">{ECOSYSTEM.map(([title, detail], i) => <motion.div key={title} whileHover={{ y: -3, scale: 1.01 }} className={`rounded-2xl border border-[var(--shield-border)] bg-[oklch(0.08_0.012_165/.78)] p-4 backdrop-blur-xl ${i === 0 ? "col-span-2" : ""}`}><div className="text-xs font-semibold">{title}</div><div className="mt-1 text-[9px] leading-4 text-[var(--shield-text-faint)]">{detail}</div></motion.div>)}</div><div className="relative mt-3 text-center text-[8px] uppercase tracking-[.18em] text-[var(--shield-text-faint)]">Potential ecosystem · future roadmap</div></div><div><Eyebrow><Network className="h-3.5 w-3.5"/>Built to become a layer</Eyebrow><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Grow beyond the first workflow.</h2><p className="mt-4 text-sm leading-7 text-[var(--shield-text-dim)]">The long-term opportunity is an ecosystem around the journey. Potential integrations can make the agent more useful while partners gain a contextual route into the student lifecycle.</p><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-[var(--shield-border)] px-3 py-1.5 text-[9px] font-semibold uppercase tracking-[.15em] text-[var(--shield-text-faint)]"><Plug className="h-3 w-3"/>Future integrations</div></div></div></Reveal></div></section>

    <section className="relative w-full border-t border-[var(--shield-border)] py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="rounded-[26px] border border-[oklch(0.74_0.17_162/.24)] bg-[oklch(0.15_0.02_165/.72)] p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[1fr_.65fr] lg:items-center"><div><Eyebrow><Sparkles className="h-3.5 w-3.5"/>Business model direction</Eyebrow><h2 className="mt-3 text-2xl font-semibold sm:text-3xl">Start with the student. Build toward the ecosystem.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--shield-text-dim)]">Premium student workflows first; potential institution and partner distribution later. These are strategic directions, not current revenue or signed partnerships.</p></div><div className="rounded-2xl border border-[var(--shield-border)] bg-[oklch(0.09_0.012_165/.65)] p-5"><Shield className="h-5 w-5 text-[oklch(0.85_0.19_158)]"/><h3 className="mt-3 text-sm font-semibold">Control is part of the product.</h3><p className="mt-2 text-[11px] leading-5 text-[var(--shield-text-dim)]">The agent can research and prepare. External actions remain approval-gated.</p><button type="button" onClick={() => onNavigate?.("agent")} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[var(--shield-text)] px-4 py-2.5 text-xs font-semibold text-[var(--shield-ink)]">Open the agent <ArrowRight className="h-3.5 w-3.5"/></button></div></div></div></Reveal></div></section>
  </>;
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.18em] text-[oklch(0.85_0.19_158)]">{children}</div>; }
