"use client";

import { motion } from "framer-motion";
import { ArrowRight, Bot, BriefcaseBusiness, CalendarClock, FileCheck2, Globe2, Layers3, Network, Plug, Shield, Sparkles, Target } from "lucide-react";
import Reveal from "./Reveal";
import JourneyEngine3D from "./JourneyEngine3D";

const PHASES = [
  { n: "01", title: "Choose the move", icon: Globe2, detail: "Destination, course, university fit, career target and constraints become one working context." },
  { n: "02", title: "Secure the move", icon: CalendarClock, detail: "Applications, funding, visa, deadlines and pre-departure work are sequenced around your actual route." },
  { n: "03", title: "Build career capital", icon: FileCheck2, detail: "Your study period becomes a career-building system: skills, projects, evidence, network and experience." },
  { n: "04", title: "Land the role", icon: BriefcaseBusiness, detail: "Target roles, employers, applications and interviews connect back to the outcome you chose at the start." },
];

const ECOSYSTEM = [["Discover", "Universities, courses and country intelligence"], ["Prepare", "Email, calendar and document workflows"], ["Move", "Housing, visa and arrival services"], ["Career", "Jobs, networking and employer pathways"]];

export default function HomeShowcase({ onNavigate }: { onNavigate?: (view: string) => void }) {
  return <>
    <section className="relative w-full border-t border-[var(--shield-border)] py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <Reveal className="max-w-3xl"><Eyebrow><Layers3 className="h-3.5 w-3.5" />Why this exists</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">The problem is not a lack of information. It is a lack of continuity.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[var(--shield-text-dim)] sm:text-base">Students move between university portals, spreadsheets, consultants, email, visa checklists, job boards and networking tools. Each system sees one slice. AbroadShield is designed around the journey itself.</p></Reveal>
        <Reveal delay={0.08} className="mt-12"><div className="grid gap-3 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] border border-[var(--shield-border)] bg-[var(--shield-ink-2)] p-6 sm:p-8"><div className="text-[9px] font-bold uppercase tracking-[.2em] text-[var(--shield-text-faint)]">The fragmented stack</div><div className="mt-6 space-y-2">{["Study choice", "Applications", "Visa & relocation", "Life during study", "Networking & jobs"].map((item, i) => <motion.div key={item} initial={{ opacity: 0, x: -12 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }} className="flex items-center gap-3 rounded-xl border border-[var(--shield-border)] bg-[oklch(0.12_0.016_165)] px-4 py-3"><span className="text-[9px] font-bold text-[var(--shield-text-faint)]">0{i + 1}</span><span className="text-xs font-medium text-[var(--shield-text-dim)]">{item}</span></motion.div>)}</div></div><div className="relative overflow-hidden rounded-[28px] border border-[oklch(0.74_0.17_162/.25)] bg-[oklch(0.15_0.018_165)] p-6 sm:p-8"><div className="pointer-events-none absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[oklch(0.74_0.17_162/.1)] blur-3xl"/><div className="relative flex h-full flex-col justify-between"><div><div className="text-[9px] font-bold uppercase tracking-[.2em] text-[oklch(0.85_0.19_158)]">The AbroadShield thesis</div><h3 className="mt-3 max-w-xl text-2xl font-semibold sm:text-3xl">One context layer that can carry the student from decision to career.</h3><p className="mt-4 max-w-xl text-sm leading-6 text-[var(--shield-text-dim)]">The product does not try to replace every service. It gives the student one strategic layer that understands what has happened, what matters next and where an agent can safely help.</p></div><div className="mt-8 flex flex-wrap gap-2"><Pill>Profile</Pill><Pill>Journey</Pill><Pill>Agent</Pill><Pill>Evidence</Pill><Pill>Career</Pill></div></div></div></div></Reveal>
      </div>
    </section>

    <section className="relative w-full py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="mb-8 flex items-end justify-between gap-6"><div className="max-w-2xl"><Eyebrow><Bot className="h-3.5 w-3.5" />See the engine</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">Your AI should understand the route, not just answer the question.</h2><p className="mt-5 text-sm leading-7 text-[var(--shield-text-dim)] sm:text-base">A visual model of the product thesis: persistent context enters the engine, the journey determines priority, evidence informs the next move, and control stays with the student.</p></div><button type="button" onClick={() => onNavigate?.("journey")} className="hidden shrink-0 items-center gap-2 rounded-full border border-[var(--shield-border)] px-4 py-2.5 text-xs font-semibold text-[var(--shield-text-dim)] transition hover:-translate-y-0.5 hover:bg-[oklch(0.18_0.022_165/.7)] sm:inline-flex">Open the cockpit <ArrowRight className="h-3.5 w-3.5"/></button></div><JourneyEngine3D /></Reveal></div></section>

    <section id="journey" className="relative w-full border-t border-[var(--shield-border)] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal className="max-w-3xl"><Eyebrow><Target className="h-3.5 w-3.5"/>The full journey</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">Four phases. One evolving strategy.</h2><p className="mt-5 text-sm leading-7 text-[var(--shield-text-dim)] sm:text-base">The route stays visible while the current mission changes. That is the difference between a checklist and a journey operating system.</p></Reveal><Reveal delay={0.08} className="mt-10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{PHASES.map(({ n, title, icon: Icon, detail }, i) => <motion.button key={n} type="button" onClick={() => onNavigate?.("journey")} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ delay: i * .07 }} whileHover={{ y: -6, scale: 1.01 }} className="group rounded-[22px] border border-[var(--shield-border)] bg-[oklch(0.15_0.02_165/0.42)] p-5 text-left transition hover:border-[oklch(0.74_0.17_162/.4)] hover:bg-[oklch(0.18_0.022_165/.7)]"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold tracking-[0.18em] text-[var(--shield-text-faint)]">{n}</span><Icon className="h-4 w-4 text-[oklch(0.85_0.19_158)] transition-transform group-hover:scale-110"/></div><h3 className="mt-8 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--shield-text-dim)]">{detail}</p><span className="mt-5 inline-flex items-center gap-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-[oklch(0.78_0.08_165)]">Open in cockpit <ArrowRight className="h-3 w-3"/></span></motion.button>)}</div></Reveal></div></section>

    <section className="relative w-full py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div className="overflow-hidden rounded-[28px] border border-[var(--shield-border)] bg-[oklch(0.1_0.013_165)] p-2"><img src="/sections/ecosystem-map.svg" alt="Illustration of potential future AbroadShield ecosystem connections" className="h-auto w-full rounded-[22px]" loading="lazy"/></div><div><Eyebrow><Network className="h-3.5 w-3.5"/>Built to become a layer</Eyebrow><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">A platform can grow beyond the first workflow.</h2><p className="mt-4 text-sm leading-7 text-[var(--shield-text-dim)] sm:text-base">The long-term opportunity is an ecosystem around the journey — not a claim that these relationships already exist. Potential integrations can make the agent more useful while partners gain a contextual route into the student lifecycle.</p><div className="mt-7 grid gap-2 sm:grid-cols-2">{ECOSYSTEM.map(([title, detail], i) => <motion.div key={title} whileHover={{ y: -3 }} transition={{ duration: .2 }} className="rounded-2xl border border-[var(--shield-border)] bg-[var(--shield-ink-2)] p-4"><div className="text-xs font-semibold">{title}</div><div className="mt-1 text-[10px] leading-5 text-[var(--shield-text-dim)]">{detail}</div></motion.div>)}</div><div className="mt-5 inline-flex items-center gap-2 rounded-full border border-[var(--shield-border)] px-3 py-1.5 text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--shield-text-faint)]"><Plug className="h-3 w-3"/>Potential integrations · future roadmap</div></div></div></Reveal></div></section>

    <section className="relative w-full border-t border-[var(--shield-border)] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><div className="rounded-[30px] border border-[oklch(0.74_0.17_162/.28)] bg-[oklch(0.15_0.02_165/.75)] p-7 sm:p-10"><div className="grid gap-9 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><Eyebrow><Sparkles className="h-3.5 w-3.5"/>Business model direction</Eyebrow><h2 className="mt-4 max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">Start with the student. Build toward the ecosystem.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--shield-text-dim)]">A credible path can begin with a premium student product, then expand into institution and partner distribution once the core journey creates measurable value. These are strategic model directions — not current revenue or signed partnerships.</p><div className="mt-7 grid gap-2 sm:grid-cols-3">{["Premium journey intelligence and agent workflows.", "Potential B2B / B2B2C journey infrastructure.", "Potential contextual distribution and services."].map((body, i) => <ModelCard key={body} title={i === 0 ? "Student" : i === 1 ? "Institutions" : "Partners"} body={body}/>)}</div></div><div className="rounded-2xl border border-[var(--shield-border)] bg-[oklch(0.1_0.013_165/.7)] p-6"><Shield className="h-5 w-5 text-[oklch(0.85_0.19_158)]"/><h3 className="mt-4 text-sm font-semibold">Control is part of the product.</h3><p className="mt-2 text-xs leading-6 text-[var(--shield-text-dim)]">Research and preparation can be agent-assisted. External actions stay approval-gated until the product has a verified permission path.</p><button type="button" onClick={() => onNavigate?.("agent")} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[oklch(0.98_0.005_160)] px-4 py-2.5 text-xs font-semibold text-[oklch(0.14_0.018_165)]">Open the agent <ArrowRight className="h-3.5 w-3.5"/></button></div></div></div></Reveal></div></section>
  </>;
}

function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[oklch(0.85_0.19_158)]">{children}</div>; }
function Pill({ children }: { children: React.ReactNode }) { return <span className="rounded-full border border-[var(--shield-border)] bg-[oklch(0.1_0.013_165)] px-3 py-1.5 text-[10px] text-[var(--shield-text-dim)]">{children}</span>; }
function ModelCard({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-[var(--shield-border)] bg-[oklch(0.1_0.013_165/.62)] p-4"><div className="text-xs font-semibold">{title}</div><p className="mt-1 text-[10px] leading-5 text-[var(--shield-text-dim)]">{body}</p></div>; }
